version = 0.1

[default.deploy.parameters]
stack_name = "sweet-taco"
resolve_s3 = true
s3_prefix = "sweet-taco"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false

parameter_overrides = "RedisUrl=\"YOUR_REDIS_URL\" KvUrl=\"none\" KvToken=\"none\" VapidPrivateKey=\"none\" VapidSubject=\"mailto:admin@tacotrump.space\""
